# Insercion datos t_direccion
INSERT INTO `itma2`.`t_direccion` (`codigo_postal`,`estado`,`alcaldia`,`colonia`,`calle`,`numero_interior`,`numero_exterior`) VALUES (11360,'Ciudad de México','Agricultura','Miguel Hidalgo','no se ','1','3');
INSERT INTO `itma2`.`t_direccion` (`codigo_postal`,`estado`,`alcaldia`,`colonia`,`calle`,`numero_interior`,`numero_exterior`) VALUES (01110,'Ciudad de México','Belém de las Flores','Álvaro Obregón','no se dos','s/n','s/n');
INSERT INTO `itma2`.`t_direccion` (`codigo_postal`,`estado`,`alcaldia`,`colonia`,`calle`,`numero_interior`,`numero_exterior`) VALUES (02720,'Ciudad de México','San Antonio','Azcapotzalco','maceta noche buena ','18','260');
INSERT INTO `itma2`.`t_direccion` (`codigo_postal`,`estado`,`alcaldia`,`colonia`,`calle`,`numero_interior`,`numero_exterior`) VALUES (01000,'Ciudad de México','San Ángel','Álvaro Obregón','quien sabe','25','3a');
INSERT INTO `itma2`.`t_direccion` (`codigo_postal`,`estado`,`alcaldia`,`colonia`,`calle`,`numero_interior`,`numero_exterior`) VALUES (01500,'Ciudad de México','Santa Lucía','Álvaro Obregón','san pablo','2b','12');

# Insersion datos Persona
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('1', '2', '1', '1', 'Tonantzin', 'Ponce', 'Martínez', 'POMT651123MTSLLR06', '5581928391', 'mariana@mail.com', '2000-08-19','Mexicana');
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('2', '3', '4', '2', 'Zuleima Gabriela', 'Ordoñes', 'Alanis', '00AZ900824MTSRLL08', '5571827389', 'gabriela@gmail.com', '2003-07-28','Mexicana');
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('2', '5', '5', '3', 'Marisol', 'Sanches', 'Perez', 'SAPM880429MTSRR00', '5573829182', 'marisol@gmail.com', '2001-04-14','Mexicana');
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('2', '6', '2', '4', 'Magdalena', 'Gonzalez', 'Rodriguez', 'GORM680121MTSNDG06', '5628391029', 'magda@mail.com', '2000-07-16','Mexicana');
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('1', '1', '3', '5', 'Omar Jesús', 'Peréz', 'Ramos', 'RMPOMG900321MTSDRD01', '5638291765', 'lupe@mail.com', '1999-12-28','Mexicana');
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('1', '2', '3', '2', 'Elvia', 'Garcia', 'Romero', 'RMGE950427HGRBJN07', '5590989970', 'vicent@gmail.com', '1995-04-27','Mexicana');
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('2', '2', '1', '3', 'Ilse Irlanda', 'Najera', 'Chavéz', 'CVNII941203MCCCRN07', '5676891122', 'ali@gmail.com', '1994-12-03','Mexicana');
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('1', '1', '5', '4', 'Regina', 'Cruz', 'Gimenez', 'AURS931106HSPGZN00', '5564678990', 'jonana@gmail.com', '1993-11-06','Mexicana');
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('2', '1', '4', '1', 'Nelida', 'Cañedo', 'Alvarado', 'AVCN950608MNLNZN07', '5670708080', 'lindisima@gmail.com', '1995-06-08','Mexicana');
INSERT INTO `itma2`.`t_persona` (`id_cat_sexo`, `id_cat_estado_civil`, `id_cat_escolaridad`, `fk_direccion`, `nombre_persona`, `apellido_paterno`, `apellido_materno`, `curp`, `telefono`, `correo`, `fecha_nacimiento`, `nacionalidad`) VALUES ('2', '1', '3', '5', 'Myrna', 'Linares', 'Altamirano', 'AMLM950429MCHRRR09', '5564647880', 'lau@gmail.com', '1995-04-29','Mexicana');

# Insersion datos Usuario
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('1', '1', 0, 'dir_milpaalta2@tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('4', '2', 0, 'admin_milpaalta2@tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('5', '3', 0, 'acad_milpaalta2@tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('6', '4', 0, 'se_milpaalta2@tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('7', '5', 0, 'dep_milpaalta2@tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('8', '6', 0, 'dda_milpaalta2@tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('3', '7', 0, 'marisol.sa@milpaalta2.tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('2', '8', 0, 'l211190001@milpaalta2.tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('9', '9', 0, 'rf_milpaalta2@tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
INSERT INTO `itma2`.`t_usuario` (`fk_persona`, `id_cat_rol`, `estado`, `correo_usuario`, `password`) VALUES ('10', '10', 0, 'rh_milpaalta2@tecnm.mx', '$2y$10$HOnh9gDtYLeKM7nB/Zpi8eSBvIJyy7CJYNotccQhmmyyibYQZNUN2');
